dateModified: 1682095795
email:
  fromEmail: roy@perfectwebteam.nl
  fromName: Stage
  replyToEmail: null
  template: null
  transportSettings:
    command: $SENDMAIL
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: assets
    settings:
      path: '@root/htdocs/web/assets'
    type: craft\fs\Local
    url: '@web/web/assets'
meta:
  __names__:
    2b4e143e-7528-4969-ab52-6165ae2914e6: Submenutekst # Submenutekst
    3a7302dc-ffd8-4c9d-bdc3-49ba3126e6d3: 'Display content' # Display content
    3cb2174e-8b70-4419-9324-8292533a014c: Link # Link
    5c79a5b9-c5f6-47a9-bc5b-db9ef8038308: 'Contact Form' # Contact Form
    7ab04376-05db-45f0-99a3-539c362ef563: Stage # Stage
    9aaba2fb-2158-4ef3-b23f-48b48f7c89d3: 'Preview Image ' # Preview Image 
    18f61b71-9a64-4293-9a38-968dd55c5e91: ContactPaginaTekst # ContactPaginaTekst
    42ba97e6-8304-45bc-9fc7-c69cf07d793d: 'Algemenevoorwaarden ' # Algemenevoorwaarden 
    52fb42a9-b5aa-40bf-b186-7138c8e4d874: footerLinkGroup # footerLinkGroup
    66e39328-60c8-4f6d-b959-8c8773b44d98: Contact # Contact
    68fc4b1b-ee3a-4402-a858-73ee024b6726: 'Link Group ' # Link Group 
    98d115a6-cdb7-4331-b2a6-0f15852eea1c: New # New
    155bba92-5c79-4460-aed1-3cd69e769831: 'Home page' # Home page
    424aa4ad-fd1e-47d4-beb0-c4376ab2fb66: Default # Default
    624e1077-2ee5-493b-8a3f-626fadbddfd9: 'Link Item' # Link Item
    78362d11-2362-49b1-8c56-943314bf1286: footerLinks # footerLinks
    90734f86-d637-45c2-8dff-7265a51843ca: Common # Common
    4653194c-0478-4c38-8488-2887e8272276: 'Home page' # Home page
    a070c64f-5c6e-4964-9ee8-cf31a84611eb: Image # Image
    a9a397f1-ca1c-4bfa-9222-f1d531c01720: footerLink # footerLink
    b5f9038a-af7a-4077-b032-b9ae4a5977d0: Stage # Stage
    b9eab774-ce40-4462-a7d9-23a0be96650f: public # public
    b9744da2-0f38-4a28-8e06-55ca5eb8a847: Nieuwspaginatekst # Nieuwspaginatekst
    df929250-2dea-4e33-8557-1898395910e1: Mailer # Mailer
    e2acc153-09da-46ae-861a-bfd4fb607a0f: Contact # Contact
    ecad64de-f06b-4d1c-8c67-951bc9432165: ContactformulierLinkGroup # ContactformulierLinkGroup
    ecc43404-6e23-417e-816e-98745ef5f49a: 'Text ' # Text 
plugins:
  formie:
    edition: standard
    enabled: true
    licenseKey: 91LV8PAD4G4LZJZASKYY501Q
    schemaVersion: 2.0.8
    settings:
      ajaxTimeout: 10
      alertEmails: null
      captchas:
        __assoc__:
          -
            - recaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Recaptcha
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - recaptcha
                      -
                        - type
                        - v3
                      -
                        - size
                        - normal
                      -
                        - theme
                        - light
                      -
                        - badge
                        - bottomright
                      -
                        - language
                        - en
                      -
                        - minScore
                        - 0.5
                      -
                        - scriptLoadingMethod
                        - asyncDefer
          -
            - hcaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Hcaptcha
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - hcaptcha
                      -
                        - size
                        - normal
                      -
                        - theme
                        - light
                      -
                        - language
                        - en
                      -
                        - minScore
                        - 0.5
                      -
                        - scriptLoadingMethod
                        - asyncDefer
          -
            - duplicate
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Duplicate
                -
                  - enabled
                  - '1'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - duplicate
          -
            - honeypot
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Honeypot
                -
                  - enabled
                  - '1'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - honeypot
          -
            - javascript
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Javascript
                -
                  - enabled
                  - '1'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - javascript
      defaultDateDisplayType: calendar
      defaultDateTime: null
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: verbb\formie\positions\AboveInput
      defaultLabelPosition: verbb\formie\positions\AboveInput
      defaultPage: forms
      emptyValuePlaceholder: 'No response.'
      enableBackSubmission: true
      enableCsrfValidationForGuests: true
      enableUnloadWarning: true
      includeDraftElementUsage: false
      includeRevisionElementUsage: false
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      pluginName: Formie
      queuePriority: null
      saveSpam: true
      sendEmailAlerts: false
      sentNotifications: true
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamEmailNotifications: false
      spamKeywords: ''
      spamLimit: 500
      useQueueForIntegrations: true
      useQueueForNotifications: true
  language-redirector:
    edition: standard
    enabled: true
    licenseKey: GLP40DMFMCJWMPDVEOPP4LSS
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  stage:
    edition: standard
    enabled: true
    schemaVersion: '1'
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: solo
  live: true
  name: Stage
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: Europe/Amsterdam
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
